### ISSUE TITLE
chef-server-ctl user-create throws error if email address has a . in it

### ISSUE THREAD

**Issue by jstange** [opscode/chef-server#51] opened 2014-12-31 04:15 UTC
That's a legit email address, per the RFC if memory serves. Also the error message is nonsensical:

*chef-server-ctl user-create foo John Q Public "john.public@example.com" some_password**
**ERROR: Conflict**
**Response: User 'foo' already exists**

The user doesn't actually exist. If I give it a more normal-looking foo@bar.com email address things work fine.

**Comment by jstange** [comment] 2015-01-01 20:36
Hm, no, it's weirder than that... my own personal address (**stange@johnstange.net**) also breaks it, but **foo@example.com** does not. Other variations of email addresses fail or succeed in a pattern I can't quite explain.

**Comment by rpattcorner** [comment] 2015-01-02 14:09
This is a critical bug for our project, rendering our chef-based tool undeployable for the typical user emails we see.

**Comment by stevendanna** [comment] 2015-01-13 12:16
@rpattcorner @jstrange Apologies that you haven't gotten a response on this yet.  I'll be looking at this today and let you know what I find.  If you have time, I'd love if someone with a reproduction case of this could send me (steve@chef.io) the contents of the /var/log/opscode/oc_erchef/ directory after the failure.

**Comment by stevendanna** [comment] 2015-01-13 13:07
@rpattcorner @jstange A quick follow up.  In the cases you found, are you certain their are no other users with the given email address in the system.  The email address must be unique as well as the username.  Unfortunately, it appears the error message returned does not give you an indication that it is actually the error message that is failing:

```
vagrant@private-chef:~$ sudo chef-server-ctl user-create foo John Q Public "john.public@example.com" some_password
-----BEGIN RSA PRIVATE KEY-----
[...SNIP...]
vagrant@private-chef:~$ sudo chef-server-ctl user-create foobar John Q Public "john.public@example.com" some_password
ERROR: Conflict
Response: User 'foobar' already exists
```

Note that I don't have a user foobar in the system, but because the email address conflicts, I get the "Conflict" error message.

**Comment by jstange** [comment] 2015-01-13 15:42
That explanation sounds like what I've been seeing. Definitely warrants a better error message...

What's the reasoning behind enforcing uniqueness with email addresses? It seems like a standard use case to have an admin identity that might conceivable be the same person as a regular user, strictly for management tasks. Also multiple users for the same person across orgs, though there are probably better ways to accomplish the latter.

**Comment by stevendanna** [comment] 2015-01-13 15:54
@jstange The uniqueness constraint for email addresses was originally put in place for Hosted Chef where password reset (and perhaps other items) are tied to email addresses:

   https://www.chef.io/account/password_resets/new

The same user account can be associated with multiple organizations, so normal users typically don't need more than one account; however, there are other use cases where it would be nice to use the same address for multiple accounts.

I'll open a new bug for the error message and then close this one out.

**Comment by jstange** [comment] 2015-01-13 16:17
Roger that. We can work around for now by aiming our generic admin user at a local machine address or something. Thanks!

**Comment by stevendanna** [comment] 2015-01-13 16:57
Closing in favor of: https://github.com/opscode/chef-server/issues/59

**Closed by stevendanna** 2015-01-13 16:57 UTC

**Comment by github0100** [comment] 2018-03-22 04:06
you may created the org-username my mistake, but every problem  has some solution.

sudo -s
chef-server-ctl org-delete learndevops        # learndevops is my org-name you may have different
