### ISSUE TITLE
intermittent 401s from Chef Server

### ISSUE THREAD

**Issue by skymob** [opscode/chef-server#5] opened 2014-10-22 18:53 UTC
I could use some guidance tracking down a frustrating intermittent issue we've been having with open source Chef Server. This issue started when we were running version 11.0.8 on CentOS 6.4 and has continued after upgrading to 11.6.1. We interact with Chef Server frequently using chef-api gem v0.5.0.

Here is an example of the error from the user's view:
```
/usr/local/var/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-api-0.5.0/lib/chef-api/connection.rb:413:in `error': The Chef Server requires authorization. Please ensure you have specified the correct client name and private key. If this error continues, please verify the given client has the proper permissions on the Chef Server. (ChefAPI::Error::HTTPUnauthorizedRequest)

    {"error":["Invalid signature for user or client 'bethany'"]}
```

Corresponding logs on Chef server:
```
=> /var/log/chef-server/erchef/requests.log.2 <==
2014-10-16T21:19:42Z erchef@127.0.0.1 method=GET; path=/cookbooks/pp-chef-server?num_versions=1; status=401; user=bethany; req_id=8tlCJk/Z9R+mPVS/ztvVzw==; msg=bad_sig; req_time=3; rdbms_time=0; rdbms_count=2;

==> /var/log/chef-server/erchef/crash.log <==
2014-10-16 21:19:42 =ERROR REPORT====
{<<"method=GET; path=/cookbooks/pp-chef-server; status=401; ">>,"Unauthorized"}

==> /var/log/chef-server/erchef/erchef.log <==
2014-10-16 21:19:42.950 [error] {<<"method=GET; path=/cookbooks/pp-chef-server; status=401; ">>,"Unauthorized"}
```
It happens for GET,POST and PUT requests for nodes, cookbooks, searches, and for many different users in our organization. Re-trying the request seconds later always works. I've yet to see a 401/bad_sig from using knife, but we also rarely use knife. I can reliably trigger the intermittent 401s by looping through calls using chef-api, but there is no pattern to the 401s. I can't reliably trigger a 401 by looping through `knife` commands. 

System load on the server is always low, plenty of available memory, and no iowait or other disk-related performance issue markers for /var/opt/chef-server/ which is a DRBD disk on SSD. Requests come in via a Heartbeat-managed virtual IP but there is no additional layering of load-balancing or proxy-ing. I feel that time sync is not a variable because all of the servers in question are synched to the same NTP server, and I've confirmed that they are not drifting or being corrected frequently. 

Any ideas what might be causing the client to only occasionally get a response of invalid signature? Should I be looking more closely at the chef-api gem rather than the chef server itself?

OS: CentOS release 6.5 (Final)
Chef Server version: chef-server-11.1.6-1.el6.x86_64
Chef-API gem version: 0.5.0

**Comment by mmzyk** [comment] 2015-01-15 19:38
All right, coming back to this, I see that my copy/paste foo failed in the last message I posted and I posted the same link to chef_wm_base line 174 three times. Go figure.

So, just to wrap up some loose ends on how the code works (I've been purposefully thinking out loud here, or maybe typing out loud, mostly because I don't know what the cause of this error is going to be, so I want to give you as much info as possible to try and solve it).

The entry point for this code is here: https://github.com/opscode/chef_wm/blob/master/src/chef_wm_base.erl#L174, in the is_authorized function.

It will move to the verify_request_signature function, here: https://github.com/opscode/chef_wm/blob/master/src/chef_wm_base.erl#L261

If this method fails, https://github.com/opscode/chef_wm/blob/master/src/chef_wm_base.erl#L287, we construct the failure message, by calling verify_request_message, and so if we follow that we can find the exact error message that you see, which is coming from here: https://github.com/opscode/chef_wm/blob/master/src/chef_wm_base.erl#L469

So that wraps up where the error message is coming from, but this doesn't tell us what is causing the error. That takes us back to the previous code tracing I was doing in the last comment.

I had traced the code across modules to chef_authn and the authenticate_user_request function, https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L422

In that function is the code that causes the error message above, https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L426

So I left off trying to find what was trigging that error path. That took me down to do_authenticate_user_request, https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L438

Following the code, no method before verify_sig will cause the error seen. The call to verify_sig is here https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L438 and the verify_sig function is just below: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L455

The code actually branches here based on the signing version used. If it is 1.0 or 1.1 it will go this path: 
https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L455
If it is 1.2 it will go this path: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L465

1.1 is the default, as defined in the code here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L86

(FYI, the macros that the ?SIGNING_VERSION strings in the code reference that define these items are located in the header file here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.hrl so that is how those values are being resolved)

Since I can't be sure the which signing version you are using from the info I have, if we go back a bit, we can see it is pulled from the headers here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L445 and is then passed along through the request. So you should be able to look at the headers being sent and see if you are using 1.0, 1.1, or 1.2 and follow the code path as appropriate.

The code that pulls the sign version from the header, if you follow the code deep enough, is here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L392 You can see it's looking for the X-Ops-Sign value to determine what the signing version is, so look for that header value in your requests.

So, if we follow the 1.0, 1.1 default path, we're going to call decrypt_sig https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L392 with the AuthSig value and the public key. decrypt_sig is here, and it branches based on if we find an RSA public key or not: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L469

However, note that if we don't find an RSA Public Key, we assume the key is encoded and try to decode it, then call decrypt_sig again. For completeness, the decode_key function is here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L494

So when decrypt_sig returns, in the 1.0 and 1.1 default Path you can see that we attempt to do what looks like an assignment here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L458. Except we passed in Plain, so what we're really doing is pattern matching. If the decrypt_sig doesn't match up with Plain, which was already passed in, then this will fail with Erlang returning an error:bad_match, which will trigger the code path seen above. Plain was set in the previous function here: https://github.com/opscode/chef_authn/blob/master/src/chef_authn.erl#L447

If we follow the 1.2 code path, we get in a similar situation:, in that in the verify_sig function for that code path we call public_key:verify and match it against true. If public_key verify doesn't return true, then we fail the match, resulting in the error seen. 

The functions that are in the public_key module and are called here are located in the core Erlang library. http://erlang.org/doc/man/public_key.html

So, to come full circle, I can't say exactly what is happening @skymob, except that for some reason the auth info being sent across is failing to authenticate properly after it reaches a very deep level where it is comparing the key and the signature. We do know that having a client with the same name as a user can cause this, but in that cause it would be expected to fail for each request, not in the pattern being seen here. 

I'd suggest trying to capture the auth info being sent from both failing and successful requests and seeing if there is a difference. Given this is an intermittent issue (meaning there doesn't seem to be a consistent reproducible case, not that it doesn't happen often), I am inclined to think this is an issue with the chef-api gem and not with the server itself, especially since knife works just fine. I am not surprised this fails across different types of requests, as this auth code is fundamental to every request made to the chef server.

Let us know if during further investigation you still think this might be a server issue, but I'm going to close this issue out for now, since I don't believe this to be a chef server issue but instead to likely be a chef-api gem issue. The chef-api gem is a community project and is not maintained by Chef, to be clear on that.

Hopefully this helps @skymob. Good luck figuring it out.

**Closed by mmzyk** 2015-01-15 19:38 UTC

**Comment by skymob** [comment] 2015-01-15 19:48
@mmzyk, this makes sense. Thanks again for your very thorough research!

**Comment by phene** [comment] 2015-01-22 22:04
I tried filing this issue with the chef-api gem, but the maintainer is still unconvinced. https://github.com/sethvargo/chef-api/issues/32

**Comment by mmzyk** [comment] 2015-02-06 14:27
@phene For better or worse, the only reports I've seen of this happening are with the chef-api gem, which isn't a Chef maintained project. Beyond what I've already investigated I don't have the bandwidth to devote to trying to track this down, especially since I don't personally use the chef-api gem. The maintainer maybe right or wrong, but it's likely going to be up to one of the users of the chef-api gem to try and track this down or come up with a consistently reproducible case. Hopefully the code paths I've laid out above can be helpful to anyone who wants to try and track this down.

**Comment by neurogenesis** [comment] 2015-02-20 20:53
also having this problem intermittently.

**Comment by spuder** [comment] 2015-07-13 05:03
I can reproduce this. I've covered the full details with scripts and tcp dumps here: 

https://github.com/sethvargo/chef-api/issues/32#issuecomment-120805618

**Comment by stevendanna** [comment] 2015-07-14 07:31
@spuder Thanks for the detailed investigation.  I'll try to take a look at the issue this week.

**Comment by stevendanna** [comment] 2015-08-02 17:38
@spuder If you could retry your various tests with https://github.com/sethvargo/chef-api/pull/39, I'd love to know if that solves it for you.
